vtdriverio/vtdriver

dependency-reduced-pom.xml
pom.xml

* updated to grpc 1.41.0
* updated to jetcd 0.5.11

Update version of GRPC & JETCD

---

pom.xml

upgrade log4j

---

pom.xml

update jackson version to solve #

upgrade faster-jackson

---

src/main/java/com/jd/jdbc/discovery/HealthCheck.java
src/main/java/com/jd/jdbc/queryservice/CombinedQueryService.java
src/main/java/com/jd/jdbc/queryservice/IQueryService.java
src/main/java/com/jd/jdbc/queryservice/NativeQueryService.java
src/main/java/com/jd/jdbc/util/NetUtil.java
src/main/java/com/jd/jdbc/vitess/VitessDriver.java
src/main/java/com/jd/jdbc/vitess/VitessJdbcProperyUtil.java
src/main/java/com/jd/jdbc/vitess/VitessPreparedStatement.java

###changes
- fix NPE occurred when target Changed
closes #25

fix NPE occurred when target Changed

---

src/main/java/com/jd/jdbc/Executor.java
src/main/java/com/jd/jdbc/engine/LimitEngine.java
src/main/java/com/jd/jdbc/engine/OrderedAggregateEngine.java
src/main/java/com/jd/jdbc/engine/ProjectionEngine.java
src/main/java/com/jd/jdbc/engine/RouteEngine.java
src/main/java/com/jd/jdbc/engine/SubQueryEngine.java
src/main/java/com/jd/jdbc/evalengine/Arithmetic.java
src/main/java/com/jd/jdbc/evalengine/EvalEngine.java
src/main/java/com/jd/jdbc/planbuilder/PlanBuilder.java
src/main/java/com/jd/jdbc/planbuilder/PrimitiveBuilder.java
src/main/java/com/jd/jdbc/planbuilder/Symtab.java
src/main/java/com/jd/jdbc/queryservice/StreamIterator.java
src/main/java/com/jd/jdbc/sqlparser/utils/StringUtils.java
src/main/java/com/jd/jdbc/vitess/VitessStatement.java
src/main/java/com/jd/jdbc/vitess/resultset/ResultSetUtil.java
src/test/java/com/jd/jdbc/engine/CharEncodingTest.java
src/test/java/com/jd/jdbc/planbuilder/AbstractPlanTest.java
src/test/resources/engine/selectengine/calculate_dual_case.json

unresolved problems:
1. dual
```sql
select count(1) // unsupport
select .2, 2. // error
```
2. Stream+union
```sql
select id from user_extra union all select id from user_metadata
column 1 getTableName: expected user_extra, but user_metadata
```
See https://github.com/vtdriverio/vtdriver/issues/29.

fix some incorrect metadata

---

src/main/java/com/jd/jdbc/Executor.java
src/test/java/com/jd/jdbc/vitess/VitessDriverConsolidatorTest.java

1. fix: consolidator keeps reading expired response in high concurrency scenarios
2. skip transaction.
closes #31

Fix: consolidator keeps reading expired response in high concurrency scenarios

---

src/main/java/com/jd/jdbc/util/TimeUtil.java
src/main/java/com/jd/jdbc/vitess/VitessConnection.java
src/main/java/com/jd/jdbc/vitess/VitessJdbcProperyUtil.java
src/main/java/com/jd/jdbc/vitess/VitessJdbcUrlParser.java
src/test/java/com/jd/jdbc/vitess/TimezoneConfigureTest.java

1. ensure serverTimezone have be configured.
2. fix: urlParser throws an out-of-bounds exception when the parameter has no specific value.
close #36

Ensure serverTimezone have been properly configured

---

src/main/java/com/jd/jdbc/Executor.java
src/main/java/com/jd/jdbc/VSchemaManager.java
src/main/java/com/jd/jdbc/api/VtApiServer.java
src/main/java/com/jd/jdbc/api/VtHttpHandler.java
src/main/java/com/jd/jdbc/api/handler/VtStatusHandler.java
src/main/java/com/jd/jdbc/api/handler/VtVschemaRefreshHandler.java
src/main/java/com/jd/jdbc/monitor/MonitorServer.java
src/main/java/com/jd/jdbc/vitess/VitessDriver.java
src/test/java/com/jd/jdbc/api/VtApiServerTest.java

1. ApiService support multiple keyspace, fix the problem of apiSerser start multiple times under multi-threading.
2. Start apiService/monitorServer asynchronously.
close #35

ApiServer support multiple keyspace; Start apiService/monitorServer asynchronously

---

pom.xml
src/main/java/com/jd/jdbc/monitor/PlanCollector.java
src/main/java/com/jd/jdbc/monitor/QueryServiceCollector.java
src/main/java/com/jd/jdbc/monitor/SrvKeyspaceCollector.java
src/main/java/com/jd/jdbc/monitor/StatementCollector.java
src/main/java/com/jd/jdbc/monitor/TopologyCollector.java
src/test/java/com/jd/jdbc/table/batch/BatchTest.java

1. Upgrade io.prometheus.simpleclient to v0.15.0;
2. Add "_total" suffix to Counter metrics

Upgrade io.prometheus.simpleclient

---

src/main/java/com/jd/jdbc/vitess/VitessConnection.java

Lazy call to VitessConnection.buildMetaDataInfo() method
Closes #54

Lazy call to VitessConnection.buildMetaDataInfo() method

---

src/main/java/com/jd/jdbc/topo/Topo.java
src/main/java/com/jd/jdbc/topo/TopoServer.java
src/main/java/com/jd/jdbc/topo/topoproto/TopoProto.java
src/main/proto/topodata.proto

- Fixed the problem of NumberFormatException in TabletAlias parsing
- Change the uid in TabletAlias in the proto file to uint64 type
Closes #57

Fixed the problem of NumberFormatException in TabletAlias parsing

---

src/main/java/com/jd/jdbc/srvtopo/ResilientServer.java
src/main/java/com/jd/jdbc/srvtopo/SrvTopo.java
src/main/java/com/jd/jdbc/topo/etcd2topo/Etcd2TopoServer.java
src/test/java/com/jd/jdbc/topo/etcd2topo/ServerTest.java

Fix In the scenario of read-write separation takes a long time

---

src/main/java/com/jd/jdbc/tindexes/SplitTableUtil.java
src/main/java/com/jd/jdbc/tindexes/config/LogicTableConfig.java
src/main/java/com/jd/jdbc/tindexes/config/SchemaConfig.java
src/main/java/com/jd/jdbc/tindexes/config/SplitTableConfig.java
src/main/java/com/jd/jdbc/vitess/VitessDataSource.java
src/main/java/com/jd/jdbc/vitess/VitessDriver.java
src/main/java/com/jd/jdbc/vitess/VitessJdbcProperyUtil.java
src/test/java/com/jd/jdbc/table/TableTestUtil.java

* lazy load yaml split-table configuration
* support split-table configuration for spring boot starter

Split-table configuration supports loading from spring boot

---

.github/workflows/maven_test.yml
dependency-reduced-pom.xml
vtdriver-spring-boot-starter/pom.xml
vtdriver-spring-boot-starter/src/main/java/com/jd/vtdriver/spring/boot/autoconfigure/VtDriverAutoConfiguration.java
vtdriver-spring-boot-starter/src/main/java/com/jd/vtdriver/spring/boot/autoconfigure/VtDriverDataSourceInit.java
vtdriver-spring-boot-starter/src/main/java/com/jd/vtdriver/spring/boot/autoconfigure/VtDriverSplitTable.java
vtdriver-spring-boot-starter/src/main/java/com/jd/vtdriver/spring/boot/autoconfigure/properties/VtDriverSplitTableProperties.java
vtdriver-spring-boot-starter/src/main/resources/META-INF/spring.factories
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/demo/VtdriverSpringbootApplication.java
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/demo/mapper/TableMapper.java
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/demo/mapper/UserMapper.java
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/demo/model/Table.java
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/demo/model/User.java
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/testcase/DemoTest.java
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/testcase/VtDriverDataSourceTest.java
vtdriver-spring-boot-starter/src/test/java/com/jd/vtdriver/spring/boot/testcase/VtDriverSplitTableTest.java
vtdriver-spring-boot-starter/src/test/resources/application-yaml.yaml
vtdriver-spring-boot-starter/src/test/resources/application.properties

* add vtdriver-spring-boot-starter
close #61

Add vtdriver-spring-boot-starter

---

.github/workflows/maven_test.yml
pom.xml
src/main/java/com/jd/jdbc/discovery/HealthCheck.java
src/main/java/com/jd/jdbc/discovery/TabletHealthCheck.java
src/main/java/com/jd/jdbc/discovery/TopologyWatcher.java
src/main/java/com/jd/jdbc/discovery/TopologyWatcherManager.java
src/main/java/com/jd/jdbc/queryservice/TabletDialer.java
src/main/java/com/jd/jdbc/topo/Topo.java
src/main/java/com/jd/jdbc/topo/TopoStatsConnection.java
src/test/java/com/jd/jdbc/discovery/HealthCheckTest.java
src/test/java/com/jd/jdbc/queryservice/MockQueryServer.java
src/test/java/com/jd/jdbc/queryservice/TabletDialerAgent.java
src/test/java/com/jd/jdbc/topo/MemoryTopoFactory.java
src/test/java/com/jd/jdbc/topo/MemoryTopoServer.java
src/test/java/com/jd/jdbc/topo/discovery/TestHealthCheck.java
src/test/java/testsuite/TestSuite.java

- fix: healthcheck cancel
- case: mock tablet

fix: healthcheck cancel

---

.gitignore
src/main/java/com/jd/jdbc/discovery/TabletHealthCheck.java
src/main/java/com/jd/jdbc/monitor/DefaultConfig.java
src/main/java/com/jd/jdbc/monitor/HealthCheckCollector.java
src/main/java/com/jd/jdbc/monitor/HealthyCollector.java
src/main/java/com/jd/jdbc/monitor/MonitorServer.java

clean dirty vttablets in when tablet offline

clean dirty vttablets in when tablet offline

---

src/main/java/com/jd/jdbc/monitor/SqlErrorCollector.java
src/main/java/com/jd/jdbc/sqlparser/dialect/mysql/visitor/VtReplaceVariantRefExprVisitor.java
src/test/java/com/jd/jdbc/sqlparser/NormalizeRewritePutTest.java

fix sqlrewrite error，Added support for concat

 fix sqlrewrite error，Added support for concat

---

src/main/java/com/jd/jdbc/queryservice/NativeQueryService.java
src/main/java/com/jd/jdbc/vitess/AbstractVitessResultSetMetaData.java
src/main/java/com/jd/jdbc/vitess/VitessResultSetMetaData.java
src/main/java/com/jd/jdbc/vitess/resultset/AbstractDatabaseMetaDataResultSet.java
src/main/java/com/jd/jdbc/vitess/resultset/DatabaseMetaDataResultSet.java
src/main/proto/query.proto
src/test/java/com/jd/jdbc/vitess/VitessDriverDatabaseMetaDataTest.java

…nt func
add java.sql.ResultSetMetaData.isCaseSensitive func

implement DatabaseMetaDataResultSet.getStatement & ResultSetMetaData.isCaseSensitive

---

src/main/java/com/jd/jdbc/discovery/HealthCheck.java
src/test/java/com/jd/jdbc/discovery/HealthCheckTest.java

Fixing 'no valid tablet' caused by the noserving master not being offline in a dual-master setup.

Fixing 'no valid tablet' caused by the noserving master not being offline in a dual-master setup.

---

src/main/java/com/jd/jdbc/vitess/VitessJdbcProperyUtil.java
src/main/java/com/jd/jdbc/vitess/VitessJdbcUrlParser.java
src/main/java/com/jd/jdbc/vitess/mysql/VitessPropertyKey.java
src/test/java/com/jd/jdbc/engine/ASCIICharEncodingTest.java
src/test/java/com/jd/jdbc/engine/CharEncodingTest.java

Verify the encoding in the JDBC URL matches the 'file.encoding' environment variable

Verify the encoding in the JDBC URL matches the 'file.encoding' environment variable

---

src/main/java/com/jd/jdbc/planbuilder/AbstractRoutePlan.java
src/main/java/com/jd/jdbc/planbuilder/PrimitiveBuilder.java
src/main/java/com/jd/jdbc/sqlparser/dialect/mysql/visitor/VtReplaceVariantRefExprVisitor.java
src/main/java/com/jd/jdbc/sqlparser/dialect/mysql/visitor/VtSmartNormalizeVisitor.java

Support for "group by" with numeric + "having" statement.

Support for "group by" with numeric + "having" statement.
